<style>
	<?php include 'template.css'?>
</style>

<div class="tituloMapa">
    <!-- <h1 class="line-1 anim-typewriter">Els nostres departaments</h1> -->
    <h1>El procés d'elaboració</h1>
</div>

<div class="mapa">

	<img src="../../../assets/imagenes/mapa-1.png" alt="" width="674" height="490" usemap="#image-map">

	<!-- Image Map Generated by http://www.image-map.net/ -->

	<map name="image-map">
		<area target="" alt="step1" title="step1" href="../buscador/?tag=ordi" coords="25,37,28,5,51,7,75,14,84,20,63,56,46,72,34,92,34,120,15,112,3,100,24,80" shape="poly">
    	<area target="" alt="step2" title="step2" href="../buscador/?tag=malta" coords="120,143,118,89,133,61,120,34,135,23,148,23,156,27,163,35,146,61,148,72,155,82,161,98,162,125,160,146,152,154,140,156" shape="poly">
		<area target="" alt="step3" title="step3" href="../buscador/?tag=aigua" coords="218,98,206,89,193,91,185,98,188,108,193,116,197,125,183,149,184,163,185,187,189,191,203,194,215,194,219,174,216,146,209,121,218,109" shape="poly">
		<area target="" alt="step4" title="step4" href="../buscador/?tag=llúpol" coords="249,191,249,139,265,131,278,128,288,131,288,147,291,191,281,199,269,202,259,200" shape="poly">
		<area target="" alt="step5" title="step5" href="../buscador/?tag=clarificació" coords="302,253,304,224,316,212,328,203,331,183,338,179,341,184,342,193,341,201,352,210,365,223,366,238,365,249,360,257,339,265,322,265,311,260" shape="poly">
		<area target="" alt="step6" title="step6" href="../buscador/?tag=refredament" coords="396,303,398,267,407,257,430,269,431,313,421,317" shape="poly">
		<area target="" alt="step7" title="step7" href="../buscador/?tag=fermentació" coords="357,423,357,360,372,346,386,346,397,354,399,397,399,415,394,421,386,429" shape="poly">
		<area target="" alt="step8" title="step8" href="../buscador/?tag=filtratge" coords="474,375,473,341,497,331,500,304,509,298,510,313,510,325,526,339,534,350,536,370,530,379,508,390,491,385" shape="poly">
		<area target="" alt="step9" title="step9" href="../buscador/?tag=envsament" coords="533,469,537,428,538,406,545,391,557,392,570,397,572,408,592,409,599,415,599,435,599,464,598,473,589,482,579,489,565,481,544,485" shape="poly">
		<area target="" alt="step10" title="step10" href="../buscador/?tag=consum" coords="645,353,648,325,654,306,654,281,666,278,666,298,673,314,673,334,673,365,661,370,652,366" shape="poly">
    </map>

	<div id="step1" class="step">
		<p>Etapa #1</p>
		<p>
			Primeres matèries
		</p>
	</div>
	<div id="step2" class="step">
		<p>Etapa #2</p>
		<p>
			Trituració de la malta
		</p>
	</div>
	<div id="step3" class="step">
		<p>Etapa #3</p>
		<p>
			Barreja amb aigua
		</p>
	</div>
	<div id="step4" class="step">
		<p>Etapa #4</p>
		<p>
			Bullida amb els llúpols
		</p>
	</div>
	<div id="step5" class="step">
		<p>Etapa #5</p>
		<p>
			Clarificació
		</p>
	</div>
	<div id="step6" class="step">
		<p>Etapa #6</p>
		<p>
			Refredament
		</p>
	</div>
	<div id="step7" class="step">
		<p>Etapa #7</p>
		<p>
			Fermentació
		</p>
	</div>
	<div id="step8" class="step">
		<p>Etapa #8</p>
		<p>
			Filtratge
		</p>
	</div>
	<div id="step9" class="step">
		<p>Etapa #9</p>
		<p>
			Envasat
		</p>
	</div>
	<div id="step10" class="step">
		<p>Etapa #10</p>
		<p>
			Consum
		</p>
	</div>

	<script>
		<?php include 'script.js'?>
	</script>
</div>
